name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run lint
      - run: pnpm run coverage
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: |
      ${{ secrets.DOCKER_PASSWORD }} &&
      ${{ secrets.SERVER_ADDRESS }} &&
      ${{ secrets.SERVER_USERNAME }} &&
      ${{ secrets.SERVER_PASSWORD }} &&
      ${{ secrets.DOTENV_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build and Push Docker Image
        run: |
          docker build -t my-api .
          docker login -u xen0xys -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-api:latest xen0xys/my-api:latest
          docker push xen0xys/my-api:latest
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull xen0xys/my-api:latest
            docker stop my-api || true
            docker rm my-api || true
            docker run -d -p 3000:3000 -e DOTENV_KEY=${{ secrets.DOTENV_KEY }} -v /home/${{ secrets.SERVER_USERNAME }}/keys:/home/keys --name my-api --restart on-failure:2 xen0xys/my-api:latest
